### ISSUE TITLE
Eigen rooster wordt niet weergegeven

### ISSUE THREAD

**Issue by Drawer** [SpaceK33z/Pluff#124]
IK weet niet of dit al zou moeten werken. Maar na inloggen krijg ik niet mn eigen rooster gelijk te zien. Ik zie gewoon een lege pagina.

**Comment by SpaceK33z** [comment]
@Drawer, is dit inmiddels opgelost?

**Comment by Drawer** [comment]
Ja, had te maken met minoren die niet goed in het systeem stonden.
Uitzondersgevalletje dus.

**Comment by svrooij** [comment]
Hopelijk is dat inderdaad een uitzondering....
Ik ben alleen bang dat ik nu nog steeds klassen kan vinden die in het rooster net anders heten, maar het wordt steeds beter.

Misschien moet je een bericht laten zien met, klik hier om je klassen te bekijken. En klik hier om de roostermaker te mailen dat de klas de verkeerde naam heeft in het rooster.

**Comment by SpaceK33z** [comment]
Goed idee. Dat kan dan wel in een nieuw ticket ;).
