### ISSUE TITLE
Doorklikken op vak

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#141]
Je kunt al mooi doorklikken in het rooster naar docent, lokaal en klas maar ook handig is als je op vak kan doorklikken en dat je dan dus ziet welke klassen in die week dat vak hebben. Met name voor docenten een interessante feature. Het oude crappy GP Untis rooster kon ook op vak nivo het rooster tonen.

**Comment by SpaceK33z** [comment]
Is nu geïmplementeerd ;).

**Comment by JanOonk** [comment]
You're da man! Thanks
