### ISSUE TITLE
Door laten lopen van de juiste les bij dubbele lessen

### ISSUE THREAD

**Issue by ghost** [SpaceK33z/Pluff#142]

**Comment by JanOonk** [comment]
Overigens zie je nu alleen een plusje + waaraan je kan zien dat er dubbele (of zelfs 3 dubbele!) les op 1 lesuur is gepland. Is het een idee om de achtergrondkleur van het vakje ook meerdere kleuren te geven afh. van het aantal lessen op dat lesuur. Hieronder wat ideetjes:
![rooster kleurvoorstel](https://cloud.githubusercontent.com/assets/5830712/6592816/8cc6467c-c7d2-11e4-85ca-2e3316994c92.png)
