### ISSUE TITLE
Contrast tekst

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#143]
Wellicht beter om witte tekst op lichtgroene ondergrond te vermijden.
![screen3](https://cloud.githubusercontent.com/assets/5830712/6346164/cad80c00-bc0d-11e4-90e4-3fc9ad28ab49.png)

**Comment by SpaceK33z** [comment]
Gefixt dankzij @indri-indri

**Comment by JanOonk** [comment]
Thanks
