### ISSUE TITLE
Zoekbalk verdwijnt

### ISSUE THREAD

**Issue by JDouven** [SpaceK33z/Pluff#144]
Als je op het zoek-icoon klikt op de index pagina, verdwijnt de zoekbalk meteen weer na heel kort verschenen te zijn geweest. Dit komt voor op mijn iPhone 5s met Safari en met Chrome. Op een andere pagina werkt de zoekfunctie wel.

**Comment by JanOonk** [comment]
Viel mij ook al op op mijn iPhone 6 in Safari met iOS 8.1.3. Ik moet ook 2x klikken voordat ie uberhaupt komt. Wat bedoel je @JDouven trouwens met een andere pagina? Welke?

**Comment by SpaceK33z** [comment]
Hm, op mijn iOS simulator doet de focus het wel goed.

Die bug met het 2x klikken krijg ik voorlopig niet opgelost, heb een tijd geleden al een poging gedaan en voorlopig heb ik stage (aka. Pluff heeft voor mij niet zo veel prioriteit nu).

**Comment by JDouven** [comment]
@JanOonk Als ik naar de pagina vakanties ga bijvoorbeeld, werkt het wel.
@SpaceK33z Gezien het op de ene pagina wel werkt en de andere niet kun je vergelijken, maar dat Pluff niet veel prioriteit heeft snap ik zeker.

**Comment by JanOonk** [comment]
Nou dat lukt bij mij meestal niet. Het gekke is in landscape lukt het wel makkelijker maar soms ook niet?! Rare bug.

**Comment by JanOonk** [comment]
Wbt 2x klikken: de allereerste keer dat je Pluff opent (of Refresh drukt) dan doet het klikken op de zoekknop het altijd goed. Heb je 1x gezocht dan moet je daarna altijd 2x klikken.

**Comment by SpaceK33z** [comment]
Ik denk dat de problemen nu opgelost zijn. @JDouven, zou je dit kunnen testen op https://pluff-dev.iris.fhict.nl/ ?

**Comment by JDouven** [comment]
Zover ik kan zien werkt het!
