### ISSUE TITLE
Refresh bug in Internet Explorer

### ISSUE THREAD

**Issue by svrooij** [SpaceK33z/Pluff#145]
Ik zag bij een aantal docenten (op hun Fontys computer) dat pluff.nl het niet goed doet in Internet Explorer. De pagina lijkt te blijven refreshen.

Dat zou heel goed IE8 of IE9 kunnen zijn.

**Comment by SpaceK33z** [comment]
IE wordt niet ondersteund in Pluff, en ben ik ook nooit van plan. Moeten ze maar Chrome of Firefox gebruiken ;). Het moet leuk blijven voor mij om er aan te ontwikkelen.

**Comment by svrooij** [comment]
Je hebt helemaal gelijk!!! Maar wat er nu gebeurd is niet echt mooi. Je zou altijd nog een redirect naar een pagina kunnen doen die zegt installeer een fatsoenlijke browser.

Daarnaast IE8/IE9 bij ICT, wat zal ik ervan zeggen....
