### ISSUE TITLE
Beschikbaarheid docent tonen

### ISSUE THREAD

**Issue by ghost** [SpaceK33z/Pluff#146]

**Comment by indri-indri** [comment]
ok

**Comment by JanOonk** [comment]
Om dit netjes en goed om te lossen, moeten we een single source via vast format/syntax afspreken met de roostermaker, waarin de beschikbaarheid vd docent staat vermeld. Dit gebeurt nl. nu middels een mail die elk semester of schooljaar wordt verstuurd door de teamleider/roostermaker waarin elke docent zijn beschikbaarheid in een Excel sheet (per team 1 excel sheet) moet invullen.

Een alternatief is het scannen en parsen van de .html files op https://www.fhict.nl/Roosters/HuidigKwartaal/default.htm
Dit is vrij lastig, tedious werk en wellicht error-prone. Hoewel.... met een beetje regular expression magic en even alle .html bestanden ophalen uit https://www.fhict.nl/Roosters/HuidigKwartaal/<kalenderweek>/t/t00X.htm waarbij X=001 tot aantaldocenten
is het wellicht misschien wel easy piecy. Deze routine moet je dan runnen zodra er een roosterupdate is en persisten en dan deze data via webservice beschikbaar maken. Mooiste zou zijn dat dit via de bestaande FHICT API gaat.

Of alle docenten hun beschikbaarheid laten invullen in hun Sharepoint profiel bijv. https://apps.fhict.nl/sp/overzichtmedewerkers/Profile/I872272. Dan zouden we dit alleen voor de roostermaker nog even alle docentenbeschikbaarheid moeten verzamelen in 1 handig overzicht.

**Comment by JanOonk** [comment]
Ok scannen en parsen van de HTML data is by second thought best lastig vooral omdat als je 1e uur liever niet wilt worden ingepland (-2) maar er staat toch een les van 4 lesuren dan staat die -2 opeens voor alle 4 de lesuren.

Wellicht beter idee om de tijd te investeren in een goede webpagina waar alle docenten in een soort van weekrooster (met daarop alle dagen en lesuren) hun beschikbaarheid kunnen aangeven. Dit moet dan op een makkelijke manier zodat je snel bijv. een dag, dagdeel, alle 1e lesuren vd week, of willekeurige rectangle met lesuren kan vullen met beschikbaarheid.
Verder moet je ook kunnen aangeven hoeveel fte je werkt. Dit zou je ook kunnen gebruiken voor eventuele controles of constraints. Je mag bijv. als je 0,9fte werkt maar 1 dagdeel op -3 (niet beschikbaar) zetten.
Ook moet er een opmerkingen veld komen waarin bepaalde roosteraanwijzigingen of uitzonderlijke situaties staat bijv. "ma avond of di avond maar niet beide".
Alle voorkeuren van alle docenten worden opgeslagen en een overzicht kan door roostermaker realtime worden opgevraagd. Dit wordt tevens via de FHICT API beschikbaar gesteld.

**Comment by SpaceK33z** [comment]
Parsen van html gaat niet gebeuren; Pluff is een client-side applicatie en dat wil ik zo houden. Door puur de Fontys API te gebruiken is Pluff ook het betrouwbaarste.

Een webpagina waar docenten hun beschikbaarheid aangeven is geen optie; dit gaan docenten toch niet invullen.

Als @svrooij hier ondersteuning voor bouwt in de API, bouw ik het ook in voor Pluff.

**Comment by JanOonk** [comment]
Nee dat snap ik. Het was ook niet de bedoeling dat jouw applicatie dat gaat doen. Jij praat alleen met FHICT API. Ik bedoelde dat het een offline tool zou kunnen worden die de HTML parsed (yuck) als GPUntis die info niet kan exporteren OF ipv nu met Excel sheets dat we (FHICT) een intranet webpagina maken waar ze, op de manier zoals ik hierboven beschreef, hun beschikbaarheid op een makkelijke, snelle en eenduidige manier kunnen invullen zodat @svrooij (maar het heeft ook voordelen voor de roostermaker) alle beschikbaarheiddata makkelijk via FHICT API beschikbaar kan stellen aan o.a. Pluff. Maar goed dat is iets FHICT interns wat wellicht ik, @svrooij en roostermaker eens over aan tafel moeten gaan zitten.
