### ISSUE TITLE
Op zoekresultaat klikken werkt niet

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#147]
Als je zoekt kan je niet klikken op de 1 vd zoekresultaten. Alleen <enter> werkt.

**Comment by JanOonk** [comment]
Dit fixed niet het probleem. Typ maar eens "s2" in en probeer maar klas s24 met de muis(!) aan te klikken. Er gebeurt niks. Gebruik ik [enter] dan werkt het wel.

**Comment by SpaceK33z** [comment]
Deze versie staat nog niet live, over een half uurtje wel.

**Comment by JanOonk** [comment]
Oh sorry... kan ik ergens zien dat wat commited is ook live staat?
Idee om ergens op de live site een versie/build nr te tonen?

**Comment by SpaceK33z** [comment]
Goed idee, met de komende versie kan dat. In de broncode onderaan staat dan de huidige commit hash, die je ook kunt terugvinden bij elke commit (bijv. d03e89b3cc9fd1ccc083440fe9865a553e6de7f2).

**Comment by SpaceK33z** [comment]
Nieuwe versie staat live. Kun je verifiëren dat dit je probleem heeft opgelost?

**Comment by JanOonk** [comment]
Ja werkt nu thanks.
