### ISSUE TITLE
Gedrag automatisch zoeken aanpassen

### ISSUE THREAD

**Issue by ghost** [SpaceK33z/Pluff#148]

**Comment by Drawer** [comment]
Ik ben hier even ingedoken, dit lijkt mij iets in angucomplete-alt. Het stopt in ieder geval wanneer het attribuut auto-match geen true meer wordt meegegeven, dan wordt er niet automatisch gegaan naar een match. Maar ook dat is niet ideaal. 
Mijn kennis rijkt helaas niet zo ver om hier een fix voor te verzinnen. Misschien wanneer @SpaceK33z tijd heeft.

**Comment by SpaceK33z** [comment]
Ik denk dat de beste oplossing gewoon is om de `auto-match` functionaliteit van angucomplete-alt gewoon uit te zetten. We kunnen daarna evt. iets maken dat, als er 1 zoekresultaat is, automatisch naar die pagina gaat.
