### ISSUE TITLE
cursortoetsen gebruiken in zoekbalk verandert het rooster

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#149]
Als je de cursor verplaatst in de zoekbalk bijv. je hebt ingetypt "onk" en je wil nog een o tussenvoegen op de 2e plek en je gaat met je cursor 2x naar links dus, dan gaat het rooster 2 weken terug (als er tenminste weken ervoor zitten). Oplossing: de input in zoekbalk zou exclusief alleen voor die zoekbalk moeten zijn.

**Comment by SpaceK33z** [comment]
Oeps. Heeft iemand tijd / zin om dit te fixen?

**Comment by JanOonk** [comment]
Ik wil best proberen of ik een lokale dev copie kan uitchecken en aan de praat krijg en me daarna in je sourcecode gaan verdiepen en kijken of ik bepaalde bugs kan fixen. Maar meeste frameworks die jij gebruikt zijn nieuw voor mij. Heb wel kennis van HTML,CSS,PHP,jQuery,JS dus dat helpt wel. Verder net als jij beetje erg time constrained momenteeel :)
Als je een keer tijd hebt om naar FHICT te komen, desnoods einde vd dag, om me even op weg te helpen :) Maar goed ik zal eens eerst zelf proberen.

**Comment by SpaceK33z** [comment]
Graag, ik ga pas na de zomervakantie weer echt aan Pluff werken. Pull requests zal ik wel gewoon live zetten.

Angular lijkt in het begin wat complex, maar valt mee als je er gewoon mee begint te werken :).

**Comment by SpaceK33z** [comment]
Fixed by @Drawer in 96cd24968c5144528224b17bb3d9febfd262bf30.
