### ISSUE TITLE
Holidays ook tonen in rooster

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#155]
Bij Holidays staan nu de dag of dagen dat we vrij zijn, maar dit wordt niet getoond in het rooster.

Overigens is Holidays niet compleet. Ik weet niet waar deze data vandaan komt, maar bijv. Hemelvaart do/vr 14/15 mei zijn we vrij maar dit staat niet vermeld. 

Of worden beide zaken meteen meegenomen met issue #97 'Jaarplanning'?

**Comment by SpaceK33z** [comment]
Dit wordt allemaal opgelost met issue #97, maar dat gaat nog wel even duren denk ik. De data van de 'Holidays' pagina vul ik zelf. Als je de tijd hebt om de vakantiedagen weer te vullen zou dat heel fijn zijn. De vakantiedagen staan in [holidays.json](https://github.com/SpaceK33z/Pluff/blob/master/app/json/holidays.json) en de vertalingen hiervan staan in de [lang/](https://github.com/SpaceK33z/Pluff/tree/master/app/js/lang) folder.

**Comment by SpaceK33z** [comment]
Opgelost dankzij @Drawer.
