### ISSUE TITLE
Week navigator en huidige dag

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#156]
Als je door de verschillende weken heen navigeert en je wilt weer terug naar het begin dan zou daarvoor een knopje wel handig zijn bijv. een vandaag knop. Die springt dan terug naar de week van vandaag.

Verder zou handig zijn als de dag van vandaag een ander kleurtje/highlight krijgt. Tekst vd dag zelf is al genoeg.

Beide geinspireerd op Google Agenda.

Ik heb een mockup hiervan gemaakt.
![mockup](https://cloud.githubusercontent.com/assets/5830712/7198300/305c05da-e4eb-11e4-8464-a7ec5b87b66c.png)

**Comment by SpaceK33z** [comment]
> Als je door de verschillende weken heen navigeert en je wilt weer terug naar het begin dan zou daarvoor een knopje wel handig zijn bijv. een vandaag knop. Die springt dan terug naar de week van vandaag.
Dit bestaat al, als je op 'week 16' klikt ga je terug naar de huidige week.

Huidige dag ander kleurtje maken is wel een goed idee. Heb jij hier misschien tijd voor? Het is niet zo moeilijk, dus leuk issue om mee in te stappen.

**Comment by JanOonk** [comment]
>>Dit bestaat al, als je op 'week 16' klikt ga je terug naar de huidige week.

Ah kijk handig. Ik vind het wel niet echt logisch. Zeker als je verder navigeert naar bijv. wk17 of verder. Dan klik je dus op zeg week 17 waardoor hij terugspringt naar week van vandaag/week 16. Is niet echt logisch. Daardoor wist ik ook deze functionaliteit niet te vinden denk ik :)

Ik blijf bij mijn eerdere suggestie :)

Ik gebruik nu Pluff heel veel en alles wat ik tegenkom documenteer ik. Als ik tijd heb ga ik enkele dev. taken oppakken. Is mooie oefening om me eens meer te verdiepen in andere frameworks e.d. En stiekem hoop ik ook dat andere studenten enthousiast worden en mee gaan ontwikkelen. Ik promoot het bij al mijn klassen in ieder geval.
