### ISSUE TITLE
Niet volledige naam + initialen showen

### ISSUE THREAD

**Issue by Drawer** [SpaceK33z/Pluff#159]
Dit moet of aangepast worden in de API zodat het met één call meekomt of een extra call op de /me bijvoorbeeld om de voornaam + achternaam op te halen van een student.

Waarom? Ik vind het vreemd en afstandelijk staan zo met die komma en alle voorletters erbij. Daarnaast past het in mijn geval op de mobiele site niet op één regel.

**Comment by svrooij** [comment]
@Drawer (Tim) hoe zou je het dan willen tonen?

Als het een student is alleen zijn voornaam en als het een docent is zijn complete naam? Misschien kunnen we dan overwegen om dit aan te passen.

**Comment by Drawer** [comment]
Bijvoorbeeld ja. Als student weet je namelijk je eigen naam wel en kun je
toch geen roosters van een andere student opzoeken. Maar het kan denk ik
ook in Pluff aangepast worden aangezien het formaat altijd hetzelfde is.
Houd je de api wat schoner.
Op 16 jul. 2015 14:13 schreef "Stephan van Rooij" <notifications@github.com

**Comment by svrooij** [comment]
Aangezien de student inderdaad zijn eigen naam wel weet, is het misschien een idee om de roostercode (klassen/afkorting) van die persoon te tonen. Mee eens?
