### ISSUE TITLE
Angucomplete-alt kan niet geinstalleerd worden dmv npm install

### ISSUE THREAD

**Issue by Drawer** [SpaceK33z/Pluff#162]
Krijg een smerige error. Pas na stukken verwijderen erachter gekomen dat het    "angucomplete-alt": "https://github.com/ghiden/angucomplete-alt#v0.0.39",
was.

**Comment by Drawer** [comment]
Waarom is hier niet gekozen voor npm install angucomplete-alt?

**Comment by SpaceK33z** [comment]
Die liep nog een paar versies achter, en ik wilde updaten. Ik probeer er
morgen naar te kijken ;).

Met vriendelijke groeten,
Kees Kluskens

**Comment by SpaceK33z** [comment]
Bij mij lijkt het wel gewoon te werken. Ik heb een ticket aangemaakt op angucomplete-alt of hij de versie wilt publishen: ghiden/angucomplete-alt#159

**Comment by SpaceK33z** [comment]
Kun je eens kijken of het nu wel werkt voor je?

**Comment by Drawer** [comment]
Werkt weer.

Al heb ik atm wel issues met gulp-rsync.

Maar na uitcommenten van dit kan ik iig wel weer Pluff draaien. Misschien werkt t later wel weer.

**Comment by SpaceK33z** [comment]
Ah dat kan kloppen, ik gebruik `gulp-rsync` alleen voor het daadwerkelijk deployen (rsync synct files naar de pluff.nl server), maar het `rsync` commando werkt alleen op Linux / OS X.

**Comment by Drawer** [comment]
Mja, zou toch moeten werken. Werk met een Ubuntu 14.04 server in Vagrant op Windows. Eigenlijk nooit problemen mee.

**Comment by SpaceK33z** [comment]
Ah, ik ging er vanuit dat je Windows gebruikte voor development, vagrant is
idd veel verstandiger idd :). Dat is wel vreemd, daarop zou rsync wel
moeten werken.

Met vriendelijke groeten,
Kees Kluskens
