### ISSUE TITLE
Overschakelen naar nieuwe FHICT API (OAuth)

### ISSUE THREAD

**Issue by ghost** [SpaceK33z/Pluff#163]

**Comment by Drawer** [comment]
Ziet er veelbelovend uit!

**Comment by SpaceK33z** [comment]
Ik heb hier al mailcontact over gehad met Stefan, hij staat open voor suggesties, dus als die er nog zijn kunnen die gemaild worden naar hem.

Probleem is wel dat ik voorlopig geen tijd heb om Pluff om te zetten. Er is een vrij grote refactor hiervoor nodig. Als iemand hierbij wil helpen is dat zeer welkom.

**Comment by Drawer** [comment]
Ik heb dit toevallig laatst gedaan voor Facebook OAuth2 door middel van https://github.com/sahat/satellizer.
Alleen weet ik zo niet of dit ook zonder backend/database kan? Dat zou het verhaal wel wat complexer maken.

**Comment by SpaceK33z** [comment]
Volgens mij moet het wel zonder back-end kunnen, waarschijnlijk moeten we dan de token opslaan in een cookie / localstorage.

**Comment by Drawer** [comment]
Dat gebeurt sowieso al met Satellizer. Maar hij krijgt die token van de backend in mijn geval. Maar als die token dan van FHICT komt zou het idd ook moeten werken.

**Comment by SpaceK33z** [comment]
Die token zou dan idd van FHICT komen.

**Comment by SpaceK33z** [comment]
Ik ben nu hieraan begonnen in de `next` branch. Ik heb support voor oAUTH er nu nog handmatig ingebakken, maar hiervoor wil ik straks Satellizer gebruiken.

**Comment by SpaceK33z** [comment]
Satellizer werkt goed en een prototype van de nieuwe oAUTH shit is werkend. Nog te doen:

- [ ] Flow checken voor studenten.
- [x] Holidays API gebruiken.
- [ ] 'me' schedule fixen.
- [ ] Teacher dialog fixen.
- [ ] 'Free rooms' fixen.

**Comment by SpaceK33z** [comment]
Nu bijna klaar, de popup voor het inloggen werkt alleen nog niet op mobile volgens @svrooij.

**Comment by svrooij** [comment]
Het lijkt erop dat het pop-up niet werkt in de volgende browsers:
- Chrome (geeft waarschuwing, met mogelijkheid om popups toe te staan)
- Firefox (zelfde als Chrome)
- Safari (geeft ook een pop-up waarschuwing)
- mobile safari (geen waarschuwing en geen pop-up)

Het lijkt beter om gewoon te redirecten. Eventueel zou je de eerste keer een inlogknop kunnen tonen.

**Comment by SpaceK33z** [comment]
Hm, ik gebruik de [satellizer](https://github.com/sahat/satellizer) package om dit te regelen. Het lijkt erop dat die de popup nodig heeft omdat hij bij redirecten geen event listeners kan opzetten in de popup.

**Comment by SpaceK33z** [comment]
Heb het probleem gevonden: als je zonder user-interactie een popup triggert, wordt deze geblokkeerd. Als ik dit achter een inlogknop zet dan triggert geen enkele geteste browser (Chrome, Firefox, Safari, mobile safari) de popup blocker.
