### ISSUE TITLE
Lange toelichting overlapt met lesuur nummer

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#174]
Als de toelichting (...) bij een les lang is (maar niet te lang) dan overlapt ie met het lesuur nummer.

![fout](https://cloud.githubusercontent.com/assets/5830712/8125525/9699699c-10e6-11e5-983c-9bc443048d47.png)

**Comment by SpaceK33z** [comment]
@Drawer heeft dit gefixt met #175.
