### ISSUE TITLE
Na paar keer switchen van taal doet ie het niet meer

### ISSUE THREAD

**Issue by ghost** [SpaceK33z/Pluff#176]
deleted

**Comment by SpaceK33z** [comment]
Op Safari voor OS X doet 'ie het ook niet zo te zien.

**Comment by JanOonk** [comment]
Is dit al live gezet? Want op een Chrome van een student blijft ie loopen/continue refreshen en op mijn Firefox lukt het niet om een andere taal te kiezen. Maar op mijn Chrome (ook v43 net als student) doet ie het wel!
Bij een 2e student:
-Chrome v44 beta: blijft ie loopen/continue refreshen

**Comment by SpaceK33z** [comment]
In Firefox

**Comment by JanOonk** [comment]
Nog op een andere PC getest:
-FF36 en FF38 beide werken alleen NL en EN, maar niet DE
-Chrome v43 doet het wel
