### ISSUE TITLE
Bepaalde urls zijn niet beschikbaar.

### ISSUE THREAD

**Issue by svrooij** [SpaceK33z/Pluff#179]
Als je rechtstreeks naar het url van een bepaalde klas/docent gaat (zonder langs de index.html te gaan)
Krijg je page not found, dit is eigenlijk logisch want in het url staan een aantal slashes dus de webserver gaat in een map zoeken.

Misschien is dit op te lossen met een .htaccess file (in geval van Linux hosting) of door een andere manier van url routing toe te passen (met een #)

**Comment by SpaceK33z** [comment]
Dit heb ik op pluff.nl opgelost door in de nginx config index.html als default page te zetten. Weet jij toevallig of ik dit in de .htaccess gewoon kan fixen? Ik heb al lang niet meer met Apache2 gewerkt.

**Comment by svrooij** [comment]
Door een .htaccess toe te voegen met:
```
FallbackResource /index.html
```
Is het opgelost. Bron: http://stackoverflow.com/a/31545589

**Comment by SpaceK33z** [comment]
Werkt perfect zo te zien :).
