### ISSUE TITLE
Tooltip bij meerdere lessen in één uur verdwijnt niet

### ISSUE THREAD

**Issue by cascer1** [SpaceK33z/Pluff#180]
Wanneer je over het +'je gaat met je muis en daarna recht omhoog gaat dan verdwijnt de tooltip niet. Zodra je er met je muis over heen gaat verdwijnt hij wel.

[voorbeeld](https://www.ducohosting.com/screenshots/FutMtrHZx4.png)

Chrome v44, Windows 10 Pro x64

**Comment by SpaceK33z** [comment]
Dank voor het melden, zal er binnenkort naar kijken.
