### ISSUE TITLE
Geen persoonlijk rooster?

### ISSUE THREAD

**Issue by svrooij** [SpaceK33z/Pluff#182]
Naast de melding als er geen persoonlijk rooster is, is het misschien een idee om dan een pagina te tonen met de mogelijke klassen en docenten.

Dat je die (zonder in het zoek scherm te typen) meteen kan selecteren.

**Comment by SpaceK33z** [comment]
Goed idee! Kan ik dan het beste `/schedule/autocomplete/Any` gebruiken?

**Comment by svrooij** [comment]
doe maar ```/schedule/autocomplete/user``` die geeft alleen klassen en docenten terug.

**Comment by SpaceK33z** [comment]
Done, en staat live op https://pluff-dev.iris.fhict.nl/
