### ISSUE TITLE
Klassen met spaties erin werken niet

### ISSUE THREAD

**Issue by SpaceK33z** [SpaceK33z/Pluff#183]
De klas waar ik in zit heet `minor ADS71`. Dit lijkt niet te werken.

**Comment by svrooij** [comment]
https://pluff-dev.iris.fhict.nl/search/class/MINOR%20DS7#top maar deze doet het wel. Dus dat is vreemd. ligt aan het rooster denk ik.

**Comment by SpaceK33z** [comment]
Klopt, het lijkt idd aan de API te liggen. Opvallend genoeg is het rooster van deze klas wel te vinden als ik via de communistische roostersite kijk ;). Is dit te fixen?

**Comment by svrooij** [comment]
het probleem was een nvarchar(10) bij het ophalen van het rooster.
Dit issue kan worden gesloten.

**Comment by SpaceK33z** [comment]
Top! Thanks.

**Comment by SpaceK33z** [comment]
Nog klein dingetje; ik zit in deze klas, maar deze zit niet aan mijn gebruiker gekoppeld. Moet ik hiervoor bij de roostermakers zijn?
