### ISSUE TITLE
Inlog popup bij klik (ergens) en niet ingelogd

### ISSUE THREAD

**Issue by svrooij** [SpaceK33z/Pluff#184]
Als het token is verlopen (de pagina staat al een uur open) en iemand KLIKT ergens op. Dan is het token verlopen, maar dan zou je die klik kunnen gebruiken om de inlog popup te tonen.

Dat scheelt een klik voor de gebruiker.

**Comment by SpaceK33z** [comment]
Goed idee! Het zou nu moeten werken. Het is wel wat hacky...
