### ISSUE TITLE
Workshop gemist

### ISSUE THREAD

**Issue by JimVercoelen** [SpaceK33z/Pluff#186]
Sowieso netjes dat ik nou een workshop van 4 u gemist heb en ik deze mag inhalen.
![image](https://cloud.githubusercontent.com/assets/13642402/9756972/179f1e0a-56de-11e5-83d4-f495003815a2.png)
![image](https://cloud.githubusercontent.com/assets/13642402/9756983/2ab72186-56de-11e5-8954-97e362493248.png)

**Comment by SpaceK33z** [comment]
Ik snap je probleem niet.

**Comment by JimVercoelen** [comment]
Sorry was niet concreet genoeg en had dit sjagerijnig gepost.
Vergeleken bij het Fontys rooster valt er op eerste instantie niets te zien op mijn rooster, daarvoor had ik op het '+' moeten klikken voor meer informatie. Misschien als feedback dat wat er op het Fontys rooster tevoorschijn staat ook op jullie site op tevoorschijn komt zonder het plusje.
