### ISSUE TITLE
Werkt niet meer

### ISSUE THREAD

**Issue by SHEePYTaGGeRNeP** [SpaceK33z/Pluff#188]
Pluff werkt ineens niet meer voor het rooster?
![image](https://cloud.githubusercontent.com/assets/7522832/9882793/c43b2f80-5bd6-11e5-8058-1dbe85320616.png)

**Comment by DynaSpan** [comment]
Zie #187

**Comment by SpaceK33z** [comment]
#187 is nu gefixt, en daarmee waarschijnlijk ook jouw issue. Kun je het nog eens proberen?

**Comment by SHEePYTaGGeRNeP** [comment]
Ja werkt nu idd.
