### ISSUE TITLE
Verplichte scopes aangepast

### ISSUE THREAD

**Issue by svrooij** [SpaceK33z/Pluff#189]
Vanaf heden zijn de scopes fhict_people en fhict_schedule niet meer nodig. Dit maakte het toestemming scherm nodeloos ingewikkeld.

Pluff kan nu de gewenste gegevens ophalen met de scopes 'fhict' en 'fhict_personal'

**Comment by SpaceK33z** [comment]
Danku, dat is een fijne verbetering :).
