### ISSUE TITLE
IE edge mode

### ISSUE THREAD

**Issue by svrooij** [SpaceK33z/Pluff#190]
Pluff draait tegenwoordig op een domein van FHICT. Helaas hebben veel docenten ergens in internet explorer het domein fhict.nl toegevoegd voor compatibiliteit modus (en dat geldt dan voor het hele domein)

met de volgende regel kan je dit per site uitschakelen. En deze regel kan verder geen kwaad.
``` html
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```
Zou jij deze regel in de head van de pagina kunnen zetten?

**Comment by SpaceK33z** [comment]
Werkt Pluff überhaupt verder correct in IE? Ik heb een bewuste keus gemaakt om IE niet te ondersteunen (Pluff moet leuk voor mij blijven om aan te werken).

**Comment by SpaceK33z** [comment]
Heb het even getest in een VM, Pluff werkt correct in Edge [MS' nieuwe browser], maar in IE11 breekt shit:

![I love IE11](https://cloud.githubusercontent.com/assets/533616/10303240/846dff6c-6c12-11e5-84db-596b25ccc137.png)

De `redirect_uri` in de url is natuurlijk fout... Ik ga dit voorlopig niet fixen.
