### ISSUE TITLE
Accesstoken vanuit URL

### ISSUE THREAD

**Issue by svrooij** [SpaceK33z/Pluff#191]
Pluff gebruikt momenteel een inlog popup. Dit is in principe goed, maar zou het niet mooi zijn als we vanaf andere pagina's een link kunnen maken naar het goede url op de identity server en dat pluff dan meteen een token krijgt via het url?

Dus dat we op sharepoint kunnen linken naar: 
``` http 
https://tas.fhict.nl/identity/connect/authorize?client_id=pluff-implicit&scope=fhict+fhict_personal&response_type=token&redirect_uri=https://pluff.iris.fhict.nl/
```

Dan hoeft de gebruiker namelijk helemaal niet meer op inloggen te klikken en dan krijg je alleen de inlogknop als je de pagina al 2 uur open hebt.

**Comment by Drawer** [comment]
DIt kan alleen vanaf FHICT SharePoint, right? In verband met dynamic tokens
en ingelogd zijn?

2015-10-06 9:10 GMT+02:00 Stephan van Rooij <notifications@github.com>:

**Comment by SpaceK33z** [comment]
Goed idee! Wat moet ik hiervoor veranderen van mijn kant eigenlijk? De url die je geeft een unknown client ID error. `pluff-implicit` is echter dezelfde clientId die ik ook gebruik...

@Drawer, dat zou vanaf overal kunnen, zolang je maar vantevoren bent ingelogd op de portal.

**Comment by svrooij** [comment]
@SpaceK33z Ik had het url verkeerd getypt (nu aangepast). Ik denk dat je hiervoor op de hoofdpagina moet kijken of je in het url een `access_token` in het url hebt. Deze kan je vervolgens op dezelfde manier gebruiken als het accesstoken dat je via de loginknop krijgt.

``` http
https://pluff.iris.fhict.nl/#access_token=708700c9____7e&token_type=Bearer&expires_in=7200&scope=fhict%20fhict_personal
```

@Drawer als je naar bovenstaand url gaat (en je bent niet ingelogd) wordt je gevraagd om in te loggen. Daarna krijg je (als je nog nooit toestemming hebt gegevens) de vraag om toestemming te geven. Je wordt dan doorgestuurd naar pluff en dan zet dit in het fragment van de site de accesstoken. (Dus achter het #)

**Comment by SpaceK33z** [comment]
Oké duidelijk, ik zal hier binnenkort eens naar kijken.

**Comment by SpaceK33z** [comment]
Gefixt en je kunt het testen op https://pluff-dev.iris.fhict.nl :).
