### ISSUE TITLE
Rode tijdbalk staat niet op de goede plek

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#193]
Deze screenshot is van 10:27u
De rode tijdbalk staat niet op de goede plek. Deze bug is  sinds de 50 -> 45 minuten rooster wijziging.
![capture](https://cloud.githubusercontent.com/assets/13236774/10660480/97066456-78a7-11e5-89f7-2eb24c16494d.PNG)

**Comment by SpaceK33z** [comment]
Ik heb het nu aangepast, en het zou nu moeten werken op https://pluff.nl. Zou je even goed willen testen of dit werkt?

**Comment by JanOonk** [comment]
Tis nu 13:37 en zoals je ziet staat de balk nog niet correct. Getest onder FF41 en Chrome46. Overigens in IE11 doet de hele site het niet.

![pluff](https://cloud.githubusercontent.com/assets/13236774/10881906/fc90c47a-8166-11e5-92e4-5e68dac67142.PNG)

**Comment by JanOonk** [comment]
Als je toch bezig bent hiermee zou je dan ook realtime deze balk willen updaten. Dus als je na 45 minuten bijv. weer op je reeds geopenende rooster kijkt de balk een lesuur is opgeschoven. Hij blijft nu stilstaan.

**Comment by JanOonk** [comment]
Wat me ook opviel is dat als je nieuwe rooster(s) ophaalt via de zoekbox rechtsboven (al dan niet na een tijdje sinds de eerste keer) de rode tijdbalk ook niet wordt geupdate. De rode tijdbalk wordt alleen gezet als je de eerste keer een rooster inlaad of als je CTRL-F5/R(efresh) doet.

**Comment by SpaceK33z** [comment]
Graag hier een nieuw ticket voor aanmaken ;). 1 probleem, 1 ticket.

**Comment by JanOonk** [comment]
Ok ik heb seperate tickets gemaakt zie #203 en #204

**Comment by JanOonk** [comment]
Deze ticket kan ook gesloten worden @SpaceK33z . Het werkt zowel juiste positionering als realtime updaten.
