### ISSUE TITLE
4e regel rooster ontbreekt

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#194]
De 4e regel heeft ooit gewerkt maar sinds een paar maanden is ie opeens verdwenen:

Hieronder deel vh rooster van klas S22:
![capture](https://cloud.githubusercontent.com/assets/13236774/10660555/195857de-78a8-11e5-9732-2e2a01f1630b.PNG)

en de Pluff variant waarin je ziet dat "toets" ontbreekt:
![capture2](https://cloud.githubusercontent.com/assets/13236774/10660593/598896c0-78a8-11e5-9857-bd2d0c4e29fc.PNG)

**Comment by SpaceK33z** [comment]
Het lijkt erop dat deze informatie uit de API verdwenen is. De API gaf eerst per les een `description` mee waarin bijv. `toets` stond. Dit wordt nu niet meer mee gestuurd.

@svrooij, weet jij hier meer van?

**Comment by svrooij** [comment]
@JanOonk @SpaceK33z Ik zal eens kijken waar het is misgegaan.

**Comment by svrooij** [comment]
GP-Untis had het export bestand aangepast.
Ik importeer nu het nieuwe vakje. En vanaf 11-11-2015 staat de "tekst" regel ook weer in de database.

**Comment by SpaceK33z** [comment]
Danku!

**Comment by JanOonk** [comment]
Top guys!
