### ISSUE TITLE
Pauzeruimte in rooster ontbreekt deels/inconsistent

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#195]
De middagpauze van 15 min ontbreekt. Verder is de avondpauze even groot weergegeven terwijl deze 30 ipv 15 min duurt.
![pluff2](https://cloud.githubusercontent.com/assets/13236774/10882052/efd7f8c4-8167-11e5-87eb-79dbbad847d1.PNG)

**Comment by SpaceK33z** [comment]
Het heeft even geduurd, maar het is eindelijk gefixt! Ik gebruikte wat overbodig complexe berekeningen om de pauzes en het rode lijntje te berekenen; deze zijn nu drastisch versimpeld zodat het voor de volgende keer makkelijker is om het schema aan te passen.

**Comment by JanOonk** [comment]
Klopt het dat ik deze fix nog niet zie op pluff.nl, wat nu dus redirect naar iris?

**Comment by SpaceK33z** [comment]
@JanOonk: dat klopt. Je kunt het wel checken op https://pluff-dev.iris.fhict.nl
