### ISSUE TITLE
Client application is not known or is not authorized

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#196]
Ik krijg in Firefox regelmatig de foutmelding "Client application is not known or is not authorized". Ik heb drie films opgenomen achterelkaar waarin de bug wordt getoond.

Het lijkt te maken te hebben of ik rechtstreeks naar pluff.nl ga of naar https://www.pluff.nl/search/teacher/Onk
In het laatste geval werkt het nooit (of ik nu wel of niet eerst naar de portal ga). In het eerste geval (rechtstreeks naar pluff.nl) werkt het wel als ik eerst naar de portal ga.

In andere browsers krijg ik nooit deze foutmelding.

https://dl.dropboxusercontent.com/u/633233/Pluff%20bugs/pluff2.avi
https://dl.dropboxusercontent.com/u/633233/Pluff%20bugs/pluff3.avi
https://dl.dropboxusercontent.com/u/633233/Pluff%20bugs/pluff4.avi

**Comment by SpaceK33z** [comment]
Heb het kunnen reproduceren. Dank voor de melding!

**Comment by SpaceK33z** [comment]
Als je https://pluff.nl gebruikt, dus zonder de `www.`, dan werkt het wel. Ik zal in de toekomst een automatische redirect hiervoor maken.

**Comment by SpaceK33z** [comment]
Inloggen via https://www.pluff.nl/search/teacher/Onk werkt nu weer.
