### ISSUE TITLE
Pluff toont niet hetzelfde als GPUntis

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#198]
Dit is een momentopname van 0:15 snachts van zondag 8-nov op maandag 9-nov:
De roosters tonen niet dezelfde data!

GPUntis:
![ma1](https://cloud.githubusercontent.com/assets/13236774/11023396/34a0bcd8-8678-11e5-9f83-aa5da07b834d.png)

Pluff:
![ma2](https://cloud.githubusercontent.com/assets/13236774/11023397/3707de70-8678-11e5-80c0-f97ccb2b5a8d.png)

**Comment by SpaceK33z** [comment]
Hier kan ik helaas niks aan veranderen, deze data komt van de Fontys API.

**Comment by JanOonk** [comment]
Roostermaker zegt dat de oorzaak niet bij hem (hij saved/exporteert naar eigen zeggen de roosterdata correct) maar dat de roosterimport naar de API niet goed werkt?! @svrooij ?

**Comment by SpaceK33z** [comment]
@svrooij, zou je hier eens naar willen kijken?

**Comment by svrooij** [comment]
Lijkt nu opgelost, tevens wordt per les nu de property ``updatedAt`` meegegeven. Die geeft de datum weer dat een les voor het laatst is geïmporteerd. En die tijd ligt dus iets hoger dan de tijd die wordt weergegeven in het Untis rooster. Er zit max 10 minuten vertraging in het importeren.

**Comment by SpaceK33z** [comment]
Oeh die `updatedAt` is wel interessant! Daarmee zou ik ook lessen kunnen highlighten die in het laatste uur veranderd zijn, zodat een rooster wijziging beter opvalt :).

**Comment by svrooij** [comment]
Als die een bestand importeert, dan gooit die de lessen vanaf vandaag weg. Om vervolgens alle lessen uit het bestand (vanaf vandaag) in de database te zetten. Dit hoeft dus niet persé een wijziging te betekenen. Dit geeft puur aan wat de laatste importdatum is.
