### ISSUE TITLE
Error: teacher is null

### ISSUE THREAD

**Issue by martijnpc** [SpaceK33z/Pluff#199]
Hallo,

Als eerste mijn complimenten voor dit geweldige project! Eindelijk mensen die begrijpen hoe je een fatsoenlijk rooster bouwt.

Ik kwam echter wel een probleempje tegen. Als ik op dit moment naar mijn rooster wil kijken krijg ik namelijk een lege pagina te zien:
![screenshot from 2015-11-11 09 22 23](https://cloud.githubusercontent.com/assets/1781040/11086898/d5de9834-8855-11e5-93d4-c0ab506983e3.png)

Firebug laat het volgende bericht zien:
![screenshot from 2015-11-11 09 22 14](https://cloud.githubusercontent.com/assets/1781040/11086911/f77d983c-8855-11e5-8ff0-eef9b11b8fbc.png)

Dit probleem doet zich ongeveer sinds deze week voor, in zowel Firefox als Chromium.

Iemand een idee waar dit kan zitten? Ben zelf nog niet de code in gedoken, maar wil eventueel wel helpen.

**Comment by svrooij** [comment]
Het lijkt erop dat pluff nog gebruik maakt van een property dat bij elke les de docent informatie werd meegegeven. Dit is al enige tijd geleden aangepast naar een array van teachers over het totale rooster.
Zie: https://tas.fhict.nl/api/v1/swagger/ui/index#!/Schedule/Schedule_Me

Iemand die dit wil fixen?

**Comment by SpaceK33z** [comment]
Ik kan helaas dit niet fatsoenlijk testen omdat de klas waarin ik zit niet aan mijn persoonlijke rooster is gekoppeld (zelfs na een mail naar roostermakers is dit nog niet opgelost). Ik zal wel eens kijken of ik dit op de gok kan oplossen.

**Comment by SpaceK33z** [comment]
Hm op de gok testen werkt echt niet. @svrooij, is er een test account oid om dit soort dingen te kunnen testen?

**Comment by svrooij** [comment]
Ik heb de api aangepast met onderstaande code. Dit zou voor jou (@SpaceK33z) dus weer moeten werken. Maar de site lijkt het gewoon te doen dus ik weet niet helemaal waar dit probleem optreed.
``` C#
if (User.Username() == "i299925")
    return Data.Rooster.GetScheduleForQuery("C|MINOR ADS71", expandTeacher, days.Value, start);
```

**Comment by SpaceK33z** [comment]
@svrooij oh nice, thanks! Het lijkt bij mij idd gewoon goed te werken...

pluff.nl draait op dit moment de meest recente versie. Ik was van plan dit te redirecten, maar dit heb ik niet meer doorgezet toen je me mailde dat de nieuwe rooster site voorlopig geen prioriteit zou krijgen.

**Comment by svrooij** [comment]
@SpaceK33z dan kan dit issue dicht denk ik.

**Comment by martijnpc** [comment]
@svrooij Op zowel https://pluff.iris.fhict.nl als https://pluff.nl krijg ik niks te zien op de Timetable pagina.

Ben momenteel aan het kijken of ik dit kan oplossen.

**Comment by martijnpc** [comment]
Heb de oorzaak gevonden denk ik: een aantal uren in mijn rooster heeft geen docent (z/w). Hierdoor komt er een null object in de getTeacher functie in lesson.js terecht. 

![screenshot from 2015-11-11 15 35 33](https://cloud.githubusercontent.com/assets/1781040/11093327/e56deab4-8889-11e5-8872-5f144910ec34.png)

Ben momenteel bezig met een fix.

**Comment by SpaceK33z** [comment]
Ahh daar had ik idd geen rekening mee gehouden! Top.

**Comment by svrooij** [comment]
@martijnpc Dat heb je snel gevonden :+1: Ik heb begrepen van @SpaceK33z dat hij nog opzoek is naar ontwikkelaars die mee willen bouwen aan dit project. Dus daarom maak je geen pull-request met een fix?

**Comment by martijnpc** [comment]
@svrooij Ben er mee bezig :)

Als mijn planning het toe laat ga ik zeker meer contributies doen.
