### ISSUE TITLE
Link naar docentrooster werkt niet (meer)

### ISSUE THREAD

**Issue by svrooij** [SpaceK33z/Pluff#201]
Vanaf een roosterpagina kon je altijd naar het rooster van een docent springen door op de knop bekijk rooster te klikken. Maar die knop doet het niet op mijn iPad.

Overigens als in de link in het url zet werkt het wel gewoon.

**Comment by Drawer** [comment]
Werkt in Chrome desktop wel. Chrome Mobile inderdaad niet. Touchprobleempje?

**Comment by SpaceK33z** [comment]
Ik heb het kunnen reproduceren met de iOS Simulator op OS X.
Het lijkt te liggen aan het `ng-touch` package dat ik gebruik. Deze sloopt kennelijk de `ng-href` tag op een `<a>`. Zodra ik deze weghaal werkt het weer goed. Echter, ik wil `ng-touch` liefst niet verwijderen...

**Comment by SpaceK33z** [comment]
Dit is "toevallig" gefixt met het updaten van dependencies in d9c4b9cf67f10616c53ee233a1194262e64afe32. Zie ook https://github.com/angular/angular.js/commit/0dfc1dfebf26af7f951f301c4e3848ac46f05d7f, waardoor dit issue vanzelf werd gefixt.
