### ISSUE TITLE
+ popup nauwelijks te bereiken

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#206]
Als je op de + klikt en je wilt met de muis naar de popup om detail info op te vragen van bijv. de docent dan lukt het bijna nooit om daar te komen omdat de popup dan weer verdwijnt. Getest op FF en Chrome.

![bugje](https://cloud.githubusercontent.com/assets/13236774/11687057/dd22d8c2-9e84-11e5-8944-c4bcd7bb72ef.png)

**Comment by martijnpc** [comment]
Hier hetzelfde. Als je snel genoeg met de muis beweegt lijkt het echter te werken.

**Comment by SpaceK33z** [comment]
Zin om een PR'tje te doen @martijnpc? :)

**Comment by SpaceK33z** [comment]
Gefixt met 1c40c7e235e3270b6e4dc58cc5932866bc9873ba. Dit is ooit gebroken toen ik naar Angular 1.3 heb geupgrade. Angular doet kennelijk niet aan semantic versioning :(.
