### ISSUE TITLE
+ popup > docent is niet clickable

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#207]
In de + popup is wel de docent, lokaal en vak clickable maar niet docent. Terwijl dat via de zoekbalk en in het huidige rooster wel kan. Het zou mooi zijn als ook de docent in de popup clickable zou kunnen zijn.

![bugje](https://cloud.githubusercontent.com/assets/13236774/11687156/3ae69fac-9e85-11e5-9b7e-d937b5b1dee4.png)

**Comment by svrooij** [comment]
Goede oefening @JanOonk .... Je hebt je limiet aan issues bereikt. Misschien moet je er eerst maar eentje zelf oplossen :smile: :wink:

**Comment by JanOonk** [comment]
Jaja ik weet. Eerst maar eens verdiepen in de gebruikte webtechnieken... maar druk nu met MKO en mijn eigen [SQL ELearning tooltje] (http://athena.fhict.nl/elearning/).

**Comment by SpaceK33z** [comment]
@JanOonk, je bedoelt dat het vak niet klikbaar is toch? De docent kun je wel op klikken namelijk.

**Comment by SpaceK33z** [comment]
Het vak is nu klikbaar; ik ga ervan uit dat je dat bedoelde. Zoniet, laat maar weten.

**Comment by JanOonk** [comment]
Top thanks
