### ISSUE TITLE
Kalenderweek telling klopt niet

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#208]
Volgens de internationale standaard ISO 8601, zie [wiki weeknummer] (https://nl.wikipedia.org/wiki/Weeknummer#Tabellen),  is de eerste week van een jaar de week die vier of meer dagen van dat kalenderjaar bevat.
Dus dit jaar heeft ook 53 weken, echter Pluff geeft maar 52 weken aan. Het jaarrooster geeft overigens wel correct aan dat het 53 weken betreft.

**PLUFF:**
![pluffbug2](https://cloud.githubusercontent.com/assets/13236774/11781410/fe5ec364-a269-11e5-92cf-dbdbdf99f35d.png)

**JAARROOSTER:**
![pluffbug](https://cloud.githubusercontent.com/assets/13236774/11781389/d514281e-a269-11e5-8fd0-fe8508751ec1.png)

Op de wiki vind je ook berekeningen hoe je kan bepalen welk weeknummer het is:
https://nl.wikipedia.org/wiki/Weeknummer#Berekeningen

Op stackoverflow staat een Javascript functie hiervoor:
http://stackoverflow.com/questions/6117814/get-week-of-year-in-javascript-like-in-php

**Comment by cascer1** [comment]
De data kloppen niet, weektelling klopt wel.

**Comment by JanOonk** [comment]
Klopt, jij hebt getest met https://www.pluff.nl/ Er zijn echter nu 2 versies online van Pluff. De versie van FHICT werkt wel goed: https://pluff.iris.fhict.nl/

Dit is wel beetje verwarrend... Het zou beter zijn als er gewoon 1 versie te vinden was of op zijn minst ergens hier documenteren dat er 2 versies zijn met ieder eigen versie van de code.

Misschien ook een suggestie aan Kees en Stefan (de hosters van beide versies) om voor beide websites aan te geven ergens in de voetnoot vd website welke versie van de code draait.

**Comment by martijnpc** [comment]
@JanOonk Inderdaad misschien handig om iets van git describe op te nemen in de pagina.

Als ik vanavond tijd heb zal ik eens kijken of dit probleem zich ook binnen mijn ontwikkelomgeving voordoet en wat de oorzaak is.

**Comment by JanOonk** [comment]
Ik heb de ontwikkelomgeving draaiende en de laatste versie vd source opent op de verkeerde datum, weeknr is wel goed.
![bug](https://cloud.githubusercontent.com/assets/13236774/13218295/c84d8c20-d968-11e5-98c1-d5a2156f4e22.PNG)

**Comment by cascer1** [comment]
Hoezo is het niet meer gewoon op pluff.nl D:

**Comment by JanOonk** [comment]
Ik denk dat hiermee nu ook deze issue kan worden geclosed @SpaceK33z

**Comment by SpaceK33z** [comment]
Fix staat nu live op https://pluff.nl.

@JanOonk @cascer1 Op termijn is het de bedoeling om pluff.nl te redirecten naar pluff.iris.fhict.nl. Het idee hierachter is dat Fontys dan ook zelf controle heeft, waardoor ze het ook kunnen gebruiken als echte roostersite. Op lange termijn gaat dit sowieso gebeuren, ik ben namelijk over ~ 1 jaar klaar met Fontys.

Het plan is dan dat zodra ik of iemand anders iets wilt releasen, ik het eerst op pluff-dev.iris.fhict.nl kan zetten om te laten testen. Als iedereen tevreden is kan Stefan het doorzetten naar pluff.iris.fhict.nl.

**Comment by JanOonk** [comment]
Top Kees thanks voor de toelichting.

**Comment by svrooij** [comment]
@JanOonk @cascer1 het is de bedoeling op termijn de untis website te vervangen, maar dat gaat helaas minder snel dan gehoopt.
- [x] Zelf hosten
- [ ] link op huidige roostersite zetten
- [ ] link op sharepoint naar pluff
- [ ] link naar untis webpagina weghalen

**Comment by SpaceK33z** [comment]
@JanOonk @cascer1 een update op de 2 pluffs situatie: pluff.nl wordt nu geredirect naar pluff.iris.fhict.nl. Hierbij wordt ook het pad meegenomen, dus als je e.g. een bladwijzer hebt op pluff.nl/search/class/M63, blijft deze gewoon werken.
