### ISSUE TITLE
Weeknummers niet op jaarbasis maar op 'schoolbasis' maken

### ISSUE THREAD

**Issue by SpaceK33z** [SpaceK33z/Pluff#21]

**Comment by JanOonk** [comment]
Is er al een statusupdate voor deze "issue"?

**Comment by SpaceK33z** [comment]
@svrooij zei hierover het volgende, 12 dagen geleden:

> Jaarplanning en lesweken ophalen. Ja, dit wil ik ook echt al heel lang, dus er is nu een begin gemaakt met het aanbieden van deze gegevens. Nu alleen nog de gegevens invullen.

**Comment by JanOonk** [comment]
Uit betrouwbare bron vernomen (ene S. v. R.) dat de API binnenkort ondersteuning biedt om lesweken op te vragen!
Ik zou standaard lesweken (op semesterbasis dus 01-20) vermelden met tussen haakjes kalender week (kan nl. handig zijn voor sommige bijv. als je de week ook wilt opzoeken in een andere agenda of kalender of andersom je weet de kalenderweek en je wilt het lesrooster v die week erbij pakken in pluff) dus:
lesweek 01 (kal.wk. 28)

**Comment by svrooij** [comment]
Lesweken zijn inmiddels beschikbaar. Wil je die meteen meekrijgen met het rooster? Of wil je die los gaan ophalen?

**Comment by SpaceK33z** [comment]
Cool! Meekrijgen met het rooster zou het handigste zijn voor mij.

**Comment by svrooij** [comment]
@SpaceK33z Hoe zou je het willen zien? Doe maar een voorstel, dan zal ik maken.

**Comment by SpaceK33z** [comment]
Ik weet niet precies hoe de schoolweek data eruit ziet (is het een integer, timestamp oid?), maar ik zie twee mogelijkheden:

- School week met elk uur meegeven:

```json
{
    "data": [
        {
            "hoursMask": 3,
            "schoolWeek": 7
        },
        ...
    ]
}
```

- Met een extra parameter (`expandSchoolWeek` oid) meegeven, vergelijkbaar met `expandTeacher`:

```json
{
    "data": [
        {
            "hoursMask": 3,
        },
        ...
    ],
    "schoolWeeks": [
        {
            "number": 2,
            "start": "2015-11-09",
            "end": "2015-11-13"
        },
    ]
}
```

Ik denk dat de tweede oplossing het cleanste is. Voordeel van dit is ook dat ik de code van Pluff drastisch kan versimpelen, omdat de code nu zelf een array maakt van de weken in het jaar en aan de hand daarvan de juiste uren erin zet.

**Comment by svrooij** [comment]
[Dit](https://tas.fhict.nl/api/v1/swagger/ui/index#!/Schedule/Schedule_Weeks) zit nu in de api:
``` JSON
[
  {
    "title": "Lesweek 10",
    "start": "2015-11-09T00:00:00+01:00",
    "end": "2015-11-14T00:00:00+01:00"
  },
  {
    "title": "Lesweek 11",
    "start": "2015-11-16T00:00:00+01:00",
    "end": "2015-11-21T00:00:00+01:00"
  },
  {
    "title": "Lesweek 12",
    "start": "2015-11-23T00:00:00+01:00",
    "end": "2015-11-28T00:00:00+01:00"
  },
  {
    "title": "Lesweek 13",
    "start": "2015-11-30T00:00:00+01:00",
    "end": "2015-12-05T00:00:00+01:00"
  },
  ...
]
```

**Comment by SpaceK33z** [comment]
Is het ook mogelijk om dit mee te sturen met de schedule API (met `schedule/me` etc.)? Dus met een `expandWeek` oid. Hier zouden dan alle weken instaan die binnen de meegestuurde uren vallen.

**Comment by JanOonk** [comment]
Mijn lang gekoesterde feature request gaat hiermee in vervulling... goed bezig boys... als we op deze manier (meer/beter) samenwerken krijgen we veel meer gedaan en wordt Pluff nog beter dan ie al is. Top!

**Comment by svrooij** [comment]
@SpaceK33z precies zoals je hebt gevraagd. als je ``expandWeeks=true`` meestuurt krijg je een extra property ``weeks`` met de data uit [dit comment](https://github.com/SpaceK33z/Pluff/issues/21#issuecomment-155776981)

**Comment by SpaceK33z** [comment]
Na 2 jaar is het eindelijk geïmplementeerd! Het staat nu nog op https://pluff-dev.iris.fhict.nl om te testen.

**Comment by JanOonk** [comment]
Ahhh nice. Vooralsnog werkt het best ok. Ook het cachen/incrementeel ophalen rooster functioneert. Echter krijg ik een error als ik na lesweek 11 de volgende lesweek ophaal van mijn rooster. Dit komt omdat het een vakantieweek is. Ik denk dat het netter is om een leeg rooster te tonen dan de soort error page "No timetable. We couldn’t find a timetable for this week." wat nu komt.

**Comment by SpaceK33z** [comment]
Ik kan helaas geen onderscheid maken tussen 1 week waar je vrij in hebt, en een lesrooster wat helemaal niet bestaat (e.g. als ik een niet bestaande klas invul).

**Comment by JanOonk** [comment]
1 foutje ontdekt. Als je in een vakantieweek (bijv. de week na lesweek 11) het rooster opvraagt bijv. van https://pluff-dev.iris.fhict.nl/search/subject/dbs2
toont Pluff ten onrechte op 02 mei toch een les nl. die van dbs2/hmls/s22t op 09 mei 2016.

De schedule api geeft 1 dag teveel data terug. In je aanroep naar de API zal je 1 dag minder moeten ophalen dus 6 i.p.v. 7 dagen. De documentatie van de API https://api.fhict.nl/swagger/ui/index#!/Schedule/Schedule_ForQuery 
zegt dat _days _het aantal dagen is wat wordt opgehaald maar dat is dus niet zo.

**Comment by JanOonk** [comment]
> Ik kan helaas geen onderscheid maken tussen 1 week waar je vrij in hebt, en een lesrooster wat helemaal niet bestaat (e.g. als ik een niet bestaande klas invul).

Tja hoe weet je nu wanneer iemand gewoon niet bestaande parameters heeft ingevuld (bijv. class, room, teacher of subject die niet bestaat) of dat er geen lessen/data is omdat het vakantie is? Mooi zou zijn als de API een errorcode teruggeeft die aangeeft **waarom** er geen data is bijv. "none existing subject", "none exisiting room" of "no data because of holiday/school closed" oid.
In het laatste geval zou je dan een leeg weekrooster kunnen tonen, in de overige gevallen toon je de huidige "errorpage" met overzicht bestaande teachers en classes.

**Comment by SpaceK33z** [comment]
@JanOonk, de fix voor 6 dagen ipv 7 ophalen staat nu op pluff-dev.iris.fhict.nl, kun jij verifiëren dat het nu goed werkt?

Het zou idd fijner zijn als de API verschil in die 2 kan aanduiden, maar het is niet erg belangrijk vind ik.

**Comment by JanOonk** [comment]
Ja het werkt nu. Top! Let wel op dat je het weer moet aanpassen als de FHICT API _days _parameter doet wat het zou moeten doen. Waarschijnlijk kiest de ontwikkelaar ervoor om de documentatie aan te passen.

**Comment by SpaceK33z** [comment]
6 dagen is sowieso altijd goed, we willen alleen ma t/m vr ophalen.

**Comment by JanOonk** [comment]
> 6 dagen is sowieso altijd goed, we willen alleen ma t/m vr ophalen.
Kijk uit misschien gaan we wel binnenkort ook in het weekend lesgeven :)

**Comment by JanOonk** [comment]
Nog 1 dingetje: als er geen rooster wordt gevonden wordt "Kalenderweek xx" bovenaan getoond ipv "(les)week yy"

**Comment by SpaceK33z** [comment]
@JanOonk, ja dat klopt, dat is expres. Als ik geen rooster is kan je ook geen lesweek berekenen.

**Comment by JanOonk** [comment]
Eh duh Jan.
Mental Note to myself: niet reageren tijdens het koken!
