### ISSUE TITLE
Exacte search match bovenaan zoekresultaten plaatsen

### ISSUE THREAD

**Issue by JanOonk** [SpaceK33z/Pluff#215]
Usability dingetje:

Vaak weet je precies waarop je zoekt bijv. klas S22 en dan wil je dit snel kunnen typen rechtsboven in zoekvenster en dan "meteen" enter kunnen doen zonder te moeten hoveren met je muis of middels pijltjestoetsen. Nu krijg je de zoekresultaten gesorteerd:

![pluff](https://cloud.githubusercontent.com/assets/13236774/14103463/983e8cb0-f5a0-11e5-832a-628a27126834.PNG)

Als er een exacte match (case insensitive uiteraard) is dan is het het meest logisch om deze bovenaan te plaatsen (zodat je dus ook meteen enter kan doen) en de overige resultaten er meteen (gesorteerd) onder.

**Comment by JanOonk** [comment]
Thanks

**Comment by SpaceK33z** [comment]
Kun je het eens testen op https://pluff-dev.iris.fhict.nl ?

**Comment by JanOonk** [comment]
Lijkt te werken. In ieder geval bovenstaande testcase.
