### ISSUE TITLE
Efficiëntere manier van lessen ophalen

### ISSUE THREAD

**Issue by SpaceK33z** [SpaceK33z/Pluff#217]
Pluff heeft op dit moment een erg inefficiënte manier om de lessen op te halen en in het rooster te zetten. 

Dit is de huidige situatie:

1. Maak 52 weken aan, zet in elke week 5 dagen en 14 lege uren (3.640 uren in totaal).
1. Doe een API request om alle lesuren op te halen, met `days=365`.
1. Voor elk lesuur, zoek de bijbehorende week, dag en uur op en zet het hierin.

Gewilde situatie:

1. Maak één week, met 5 dagen en 14 lege uren aan (70 uren in totaal)
1. Doe een API request om alle lesuren op te halen van de huidige week.
1. Voor elk lesuur, zoek de bijbehorende dag en uur op en zet het hierin.

Het voordeel van de oude situatie is dat als je door weken navigeert, je geen extra API requests hoeft te doen, omdat je het hele rooster al inlaadt.
Het nadeel is dat het traag is, omdat je op page load al veel overbodige informatie inlaadt. Dit terwijl het door weken navigeren iets is wat je meestal niet eens nodig hebt.

**Comment by martijnpc** [comment]
Misschien een idee om naast de huidige week ook de volgende week in te laden? Als je dan naar de volgende week navigeert, kan de week daarop ingeladen worden.

Wat ook nog zou kunnen is wel een object met die 52 weken aanmaken, maar dan voor iedere week een 'isLoaded' (of iets dergelijks) field toevoegen. Dan krijg je een data structuur die naarmate de gebruiker door het rooster navigeert gevuld wordt.

**Comment by SpaceK33z** [comment]
Dat zou kunnen, maar ik wil graag af van dat object met die 52 weken, omdat dat hele model eigenlijk niet klopt; het zijn namelijk 52 weken vanaf de huidige week. Bij een jaarwisseling moet je ook het jaar gaan bijhouden (wat vreemd is) en het rooster is eigenlijk toch maar hooguit ~ 90 dagen van te voren ingevuld.

Pluff is daardoor nu best wel complex, terwijl dat eigenlijk niet nodig is (zie [week.js](https://github.com/SpaceK33z/Pluff/blob/master/app/services/week.js)).

Cachen vind ik wel een goed idee, maar zou ik liever met [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) doen; hiermee kun je API requests afvangen als de response ervan al in het geheugen staat.
