### ISSUE TITLE
own schedule is stuck on week 0 

### ISSUE THREAD

**Issue by Fontyschriek** [SpaceK33z/Pluff#218]
as a teacher: when navigating through weeks, only my schedule for week 0 is shown. 
This only happens when viewing my own schedule. Viewing other teachers schedules works as expected.

**Comment by Fontyschriek** [comment]
toevoeging (lesweek 1): omdat week 0 nu niet meer zichtbaar is, heb ik voor alle lesweken een lege pagina. Zo is pluff helaas niet bruikbaar meer. probleem is reproduceerbaar (firefox, edge, ie, ook op verschillende laptops)

**Comment by hackwerken** [comment]
https://pluff-dev.iris.fhict.nl/search/teacher/srk geeft inderdaad een leeg rooster. De console geeft de volgende fout:
```
bundle-a509a95.js:50 TypeError: Cannot read property 'lessons' of undefined
    at https://pluff-dev.iris.fhict.nl/static/bundle-a509a95.js:56:20008
    at Array.forEach (native)
    at Object.data.getTimeTable (https://pluff-dev.iris.fhict.nl/static/bundle-a509a95.js:56:19289)
    at parseTimetable (https://pluff-dev.iris.fhict.nl/static/bundle-a509a95.js:56:8797)
    at https://pluff-dev.iris.fhict.nl/static/bundle-a509a95.js:56:9144
    at processQueue (https://pluff-dev.iris.fhict.nl/static/bundle-a509a95.js:51:3278)
    at https://pluff-dev.iris.fhict.nl/static/bundle-a509a95.js:51:3545
    at Scope.$eval (https://pluff-dev.iris.fhict.nl/static/bundle-a509a95.js:51:16593)
    at Scope.$digest (https://pluff-dev.iris.fhict.nl/static/bundle-a509a95.js:51:14393)
    at Scope.$apply (https://pluff-dev.iris.fhict.nl/static/bundle-a509a95.js:51:17019)
```
Screenshot:
![screenshot from 2016-08-29 16 14 37](https://cloud.githubusercontent.com/assets/1781040/18054405/f81a0408-6e03-11e6-9ad9-2515b10809a1.png)

Ik zal straks even kijken of ik mijn ontwikkelomgeving weer kan aanzwengelen zodat ik het wat beter kan debuggen.

**Comment by hackwerken** [comment]
Probleem gevonden!

Het wordt veroorzaakt doordat Pluff uitgaat van 14 uren per dag terwijl dit er 15 zijn (geworden?). De meeste docenten hebben geen les in uur 15, waardoor het bij hen wel werkt.

Fix is onderweg.

**Comment by hackwerken** [comment]
Heb nu een pull request open staan met een fix.

Op dit moment zit deze info hardcoded in Pluff. Misschien is het mogelijk om dit via de API op te halen?

**Comment by SpaceK33z** [comment]
@hackwerken, dank voor het uitvogelen en de PR. Goed werk!

De fix staat nu live, @Fontyschriek, kun jij 'm testen?

**Comment by Fontyschriek** [comment]
thanks voor jullie snelle reactie. Zie mijn schema nu wel. Helaas loopt het alleen t/m 'lesweek 5' goed, week daarna wordt er naar 'calender week 40' en verder gesprongen. ik maak hier wel een aparte issue van

**Comment by SpaceK33z** [comment]
@Fontyschriek, dat komt waarschijnlijk omdat er voor na lesweek 5 nog geen data is.
