### ISSUE TITLE
SSL certificaat verlopen

### ISSUE THREAD

**Issue by DynaSpan** [SpaceK33z/Pluff#223]
Hey,

Op pluff.nl krijg je sinds 3 dagen een certificaat error omdat het verlopen is. pluff.iris.fhict.nl werkt wel.

**Comment by SpaceK33z** [comment]
Oepsie, zal er 's naar kijken. pluff.nl redirect trouwens gewoon naar pluff.iris.fhict.nl, dus je kunt ook die bookmarken.

**Comment by SpaceK33z** [comment]
Fixed, was een klein probleempje met de cronjob die het automatisch verversen van certs regelt via LetsEncrypt.
